# Generated by Django 5.0.2 on 2024-03-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='guests',
            field=models.SmallIntegerField(),
        ),
    ]
